### ISSUE TITLE
[Feature Request] Display a "Duration" column on Werft jobs list

### ISSUE THREAD

**Issue by felladrin** [csweichel/werft#144]
Could we also display a column with the Build Duration on Werft jobs list?
It would help us notice if the average build duration increased after some specific build.

![image](https://user-images.githubusercontent.com/418083/167625775-3c03ad68-dd26-466e-822c-5f0ae24094db.png)

Currently we can use Honeycomb to invastigate variation on jobs durations. But I think we could still benefit from having this new column.

**Comment by csweichel** [comment]
I'd be weary that the duration column would clutter this view. Also, having a single "time related" field here makes this list easier to parse.

IMHO using Honeycomb here is spot on, because it lets us have alerts and visualise trends over time.

Closing for. Please re-open if you want to pick up/continue the discussion.
