### ISSUE TITLE
[webui] Escaping issue with HTML-like strings

### ISSUE THREAD

**Issue by geropl** [csweichel/werft#54]
**Describe the bug**
The default value for annotations that are not set is `<no value>`. But the webui does not display this properly because it's parsed as HTML.

**To Reproduce**
1. Start a job with an empty annotation
```
NAMESPACE="{{ .Annotations.namespace }}"
echo "ns: '$NAMESPACE'"
```
2. See the log, observe how the `ns: ''` is printed

**Expected behavior**
See `ns: '<no value>'` printed in the ui.

**Screenshots**
![image](https://user-images.githubusercontent.com/32448529/74097412-fc6dd000-4b0b-11ea-9187-43c806ff30b2.png)

**Additional context**
Browser: Firefox

**Comment by csweichel** [comment]
Thank you for reporting this.
When showing raw logs there was an issue with showing HTML characters. This is be fixed in https://github.com/csweichel/werft/pull/55.

@geropl There's something I don't fully understand though: what do you mean with _The default value for annotations that are not set is <no value>_? The default value of annotations is/should be an empty string. is this not the case for you?

**Comment by geropl** [comment]
> The default value of annotations is/should be an empty string. is this not the case for you?

Exactly. In the `werft` version we had deployed internally the default value was `<no value>`. That's why `wipe-staging` did not work last week.
